version: '1.0'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "9000:9000"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always
