apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-redis-storage
spec:
  # default. Use `kubectl get sc` too what storage classes are configured
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
