apiVersion: v1
kind: Service
metadata:
  name: test-frontend-service
spec:
  selector:
    app: test-frontend-deployment
  ports:
  - port: 8000
    targetPort: 8080
    nodePort: 32090
  type: NodePort