apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend-deployment
        image: achatin/simple-fortune-cookie-backend:latest
        ports:
         - containerPort: 9000
        env:
          - name: REDIS_DNS
            value: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
