apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-storage
            mountPath: /var/lib/redis/data
        args: ["redis-server", "--appendonly", "yes"] # enables AOF persistance
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
